### PR TITLE
Update: add viewParams option for GetFeature requests

### PR DESCRIPTION
**Pull request by thinkingmik**
Referred to the issue #100

### CODE REVIEW

**Comment by kuzkok** [comment]
Hi, viewParams is a vendor option in geoserver WFS implementation, it is not correct to add just one for each such property. Right way is to add object property to parameters as vendorOptions and pass any of you want into it.
For example:
```
var options = {
        url: 'http://geoserver.ics.perm.ru/geoserver/ows',
        typeNS: 'topp',
        typeName: 'tasmania_cities',
        geometryField: 'the_geom',
        namespaceUri: 'testUri',
        maxFeatures: 5000,
        vendorOptions: {
          viewParams: 'from...to...',
          foo: 'bar',
          'customNS:customTag':'value'
        }
      };
      
var wfs = new L.WFST(options).addTo(map); 
```

Please change your code to this behavior.

**Comment by kuzkok** [comment]
Also dont include dist folder into PR (it is already in gitignore). Don't change package.json, and commit package-lock.json.

**Review by kuzkok — CHANGES_REQUESTED** [review]
Hi, viewParams is a vendor option in geoserver WFS implementation, it is not correct to add just one for each such property. Right way is to add object property to parameters as vendorOptions and pass any of you want into it.
For example:
```
var options = {
        url: 'http://geoserver.ics.perm.ru/geoserver/ows',
        typeNS: 'topp',
        typeName: 'tasmania_cities',
        geometryField: 'the_geom',
        namespaceUri: 'testUri',
        maxFeatures: 5000,
        vendorOptions: {
          viewParams: 'from...to...',
          foo: 'bar',
          'customNS:customTag':'value'
        }
      };
      
var wfs = new L.WFST(options).addTo(map); 
```

Please change your code to this behavior.
Dont include dist folder into PR (it is already in gitignore). Don't change package.json, and  not commit package-lock.json.

**Review by kuzkok — APPROVED** [review]

**Comment by thinkingmik** [comment]
In your opinion, this enanchment could be released with a new version `v2.0.1-beta.26` ?

Thank you!

**Comment by thinkingmik** [comment]
Any news about a possible new version `v2.0.1-beta.26` with this fix?

**Comment by bratchikov** [comment]
@kuzkok, @DubrovinPavel, please publish new beta version.

**Comment by thinkingmik** [comment]
At the moment, no version `v2.0.1-beta.26` found on npm :'-(

**Comment by kuzkok** [comment]
version `v2.0.1-beta.26` was published today https://www.npmjs.com/package/leaflet-wfst/v/2.0.1-beta.26, thanks for PR.

**Comment by thinkingmik** [comment]
Thank you very much! 👍

**Pull request merged**
